---
- job:
    name: propose-network-content-collector-base
    parent: propose-github-updates
    run: tests/playbooks/run.yaml
    required-projects:
      - name: github.com/ansible/ansible
      - name: github.com/ansible-network/network_content_collector
    vars:
      git_commit_opts: "-s"
    timeout: 3600

- job:
    name: propose-network-content-collector-base
    parent: unittests

- job:
    name: propose-network-content-collector-arista-eos
    parent: propose-network-content-collector-base
    required-projects:
      - name: github.com/ansible-network/ansible_collections.arista.eos
    vars:
      collection_namespace: arista
      collection_name: eos
      proposal_project_src: ~/src/github.com/ansible-network/ansible_collections.arista.eos

- job:
    name: propose-network-content-collector-cisco-ios
    parent: propose-network-content-collector-base
    required-projects:
      - name: github.com/ansible-network/ansible_collections.cisco.ios
    vars:
      collection_namespace: cisco
      collection_name: ios
      proposal_project_src: ~/src/github.com/ansible-network/ansible_collections.cisco.ios

- job:
    name: propose-network-content-collector-cisco-iosxr
    parent: propose-network-content-collector-base
    required-projects:
      - name: github.com/ansible-network/ansible_collections.cisco.iosxr
    vars:
      collection_namespace: cisco
      collection_name: iosxr
      proposal_project_src: ~/src/github.com/ansible-network/ansible_collections.cisco.iosxr

- job:
    name: propose-network-content-collector-cisco-nxos
    parent: propose-network-content-collector-base
    required-projects:
      - name: github.com/ansible-network/ansible_collections.cisco.nxos
    vars:
      collection_namespace: cisco
      collection_name: nxos
      proposal_project_src: ~/src/github.com/ansible-network/ansible_collections.cisco.nxos

- job:
    name: propose-network-content-collector-juniper-junos
    parent: propose-network-content-collector-base
    required-projects:
      - name: github.com/ansible-network/ansible_collections.juniper.junos
    vars:
      collection_namespace: juniper
      collection_name: junos
      proposal_project_src: ~/src/github.com/ansible-network/ansible_collections.juniper.junos

- job:
    name: propose-network-content-collector-network-cli
    parent: propose-network-content-collector-base
    required-projects:
      - name: github.com/ansible-network/ansible_collections.network.cli
    vars:
      collection_namespace: network
      collection_name: cli
      proposal_project_src: ~/src/github.com/ansible-network/ansible_collections.network.cli

- job:
    name: propose-network-content-collector-network-netconf
    parent: propose-network-content-collector-base
    required-projects:
      - name: github.com/ansible-network/ansible_collections.network.netconf
    vars:
      collection_namespace: network
      collection_name: netconf
      proposal_project_src: ~/src/github.com/ansible-network/ansible_collections.network.netconf

- job:
    name: propose-network-content-collector-vyos-vyos-base
    parent: propose-network-content-collector-base
    vars:
      collection_namespace: vyos
      collection_name: vyos
      proposal_project_src: ~/src/github.com/ansible-network/ansible_collections.vyos.vyos

- job:
    name: propose-network-content-collector-vyos-vyos
    parent: propose-network-content-collector-vyos-vyos-base
    required-projects:
      - name: github.com/ansible/ansible
      - name: github.com/ansible-network/ansible_collections.vyos.vyos

- job:
    name: propose-network-content-collector-vyos-vyos-stable29
    parent: propose-network-content-collector-vyos-vyos-base
    required-projects:
      - name: github.com/ansible/ansible
        override-checkout: stable-2.9
      - name: github.com/ansible-network/ansible_collections.vyos.vyos
        override-checkout: stable-2.9

- job:
    name: network-content-collector-base
    parent: unittests
    pre-run: tests/playbooks/pre.yaml
    run: tests/playbooks/run.yaml
    required-projects:
      - name: github.com/ansible/ansible
      - name: github.com/ansible-network/network_content_collector
    vars:
      git_commit_opts: "--allow-empty"
    timeout: 3600
    nodeset: fedora-latest-1vcpu

- job:
    name: network-content-collector-arista-eos
    parent: network-content-collector-base
    required-projects:
      - name: github.com/ansible-network/ansible_collections.arista.eos
    vars:
      collection_namespace: arista
      collection_name: eos

- job:
    name: network-content-collector-cisco-ios
    parent: network-content-collector-base
    required-projects:
      - name: github.com/ansible-network/ansible_collections.cisco.ios
    vars:
      collection_namespace: cisco
      collection_name: ios

- job:
    name: network-content-collector-cisco-iosxr
    parent: network-content-collector-base
    required-projects:
      - name: github.com/ansible-network/ansible_collections.cisco.iosxr
    vars:
      collection_namespace: cisco
      collection_name: iosxr

- job:
    name: network-content-collector-cisco-nxos
    parent: network-content-collector-base
    required-projects:
      - name: github.com/ansible-network/ansible_collections.cisco.nxos
    vars:
      collection_namespace: cisco
      collection_name: nxos

- job:
    name: network-content-collector-juniper-junos
    parent: network-content-collector-base
    required-projects:
      - name: github.com/ansible-network/ansible_collections.juniper.junos
    vars:
      collection_namespace: juniper
      collection_name: junos

- job:
    name: network-content-collector-network-cli
    parent: network-content-collector-base
    required-projects:
      - name: github.com/ansible-network/ansible_collections.network.cli
    vars:
      collection_namespace: network
      collection_name: cli

- job:
    name: network-content-collector-network-netconf
    parent: network-content-collector-base
    required-projects:
      - name: github.com/ansible-network/ansible_collections.network.netconf
    vars:
      collection_namespace: network
      collection_name: netconf

- job:
    name: network-content-collector-vyos-vyos
    parent: network-content-collector-base
    required-projects:
      - name: github.com/ansible-network/ansible_collections.vyos.vyos
    vars:
      collection_namespace: vyos
      collection_name: vyos

- project:
    check:
      jobs:
        - network-content-collector-arista-eos
        - network-content-collector-cisco-ios
        - network-content-collector-cisco-iosxr
        - network-content-collector-cisco-nxos
        - network-content-collector-juniper-junos
        - network-content-collector-network-cli
        - network-content-collector-network-netconf
        - network-content-collector-vyos-vyos
    gate:
      jobs:
        - network-content-collector-arista-eos
        - network-content-collector-cisco-ios
        - network-content-collector-cisco-iosxr
        - network-content-collector-cisco-nxos
        - network-content-collector-juniper-junos
        - network-content-collector-network-cli
        - network-content-collector-network-netconf
        - network-content-collector-vyos-vyos
    periodic:
      jobs:
        - propose-network-content-collector-arista-eos
        - propose-network-content-collector-cisco-ios
        - propose-network-content-collector-cisco-iosxr
        - propose-network-content-collector-cisco-nxos
        - propose-network-content-collector-juniper-junos
        - propose-network-content-collector-network-cli
        - propose-network-content-collector-network-netconf
        - propose-network-content-collector-vyos-vyos
        - propose-network-content-collector-vyos-vyos-stable29
    post:
      jobs:
        - propose-network-content-collector-arista-eos
        - propose-network-content-collector-cisco-ios
        - propose-network-content-collector-cisco-iosxr
        - propose-network-content-collector-cisco-nxos
        - propose-network-content-collector-juniper-junos
        - propose-network-content-collector-network-cli
        - propose-network-content-collector-network-netconf
        - propose-network-content-collector-vyos-vyos
        - propose-network-content-collector-vyos-vyos-stable29
