rm_directories:
  - "{{ collection_parent }}/plugins/modules"
  - "{{ collection_parent }}/plugins/module_utils"
  - "{{ collection_parent }}/plugins/filter"
  - "{{ collection_parent }}/plugins/action"
  - "{{ collection_parent }}/plugins/inventory"
  - "{{ collection_parent }}/playbooks"
  - "{{ collection_parent }}/docs"
  - "{{ collection_parent }}/roles"
  - "{{ collection_parent }}/test"
  - "{{ collection_parent }}/test/integration"
  - "{{ collection_parent }}/test/integration/targets"
  - "{{ collection_parent }}/test/sanity"
  - "{{ collection_parent }}/tests"
