- name: Build a list of the files in the modules directory
  find:
    paths: "{{ ansible_source_directory }}/lib/ansible/modules/network/{{ platform }}"
    patterns: "*"
  connection: local
  register: found

- name: Move the module module_source_files
  include: modules_file.yaml
  with_items: "{{ found['files'] }}"
  loop_control:
    loop_var: file
  vars:
    plugin_subdir: "modules"

- name: Build a list of the files in the action plugin directory
  find:
    paths: "{{ ansible_source_directory }}/lib/ansible/plugins/action/"
    patterns: "{{ platform }}_*"
  connection: local
  register: found

- name: Move the action plugins
  include: modules_file.yaml
  with_items: "{{ found['files'] }}"
  loop_control:
    loop_var: file
  vars:
    plugin_subdir: "action"

- name: Build a list of the files in the modules utils directory
  find:
    paths: "{{ ansible_source_directory }}/lib/ansible/module_utils/network/{{ platform }}"
    patterns: "*"
    recurse: True
  connection: local
  register: found

- name: Move the module module_source_files
  include: module_utils_file.yaml
  with_items: "{{ found['files'] }}"
  loop_control:
    loop_var: file
