- debug:
    var: file
- name: Set the basename of the file
  set_fact:
    basename: "{{ file['path']|basename }}"

- name: Set a fact for the full destination
  set_fact:
    dest: "{{ collection_parent}}/plugins/{{ plugin_subdir }}/{{ basename }}"

- name: Ensure the dest directory exists
  file:
    path: "{{ dest|dirname }}"
    state: directory

- name: "Copy {{ file['path'] }} into the collection directory structure"
  copy:
    src: "{{ file['path'] }}"
    dest: "{{ dest }}"

- name: "In the case the module starts with an _, add a link, this is a known bug in core"
  block:
    - set_fact:
        linkname: '{{ basename|regex_replace("^_(.*)", "\1") }}'

    - set_fact:
        linkpath: "{{ collection_parent}}/plugins/modules/{{ linkname }}"

    - name: Create a symbolic link
      file:
        src: "{{ basename }}"
        dest: "{{ linkpath }}"
        state: link

  when: basename.startswith('_' + collection_name)



- name: Update the files import statements
  include: update_file.yaml
  vars:
    file_path: "{{ dest }}"
