
- set_fact:
    dest: "{{ collection_parent }}/plugins{{ file['path'].split('lib/ansible')[1] }}"

- name: Ensure the dest directory exists
  file:
    path: "{{ dest|dirname }}"
    state: directory

- name: "Copy {{ file['path'] }} into the collection directory structure"
  copy:
    src: "{{ file['path'] }}"
    dest: "{{ dest }}"

- name: Update the files import statements
  include: update_file.yaml
  vars:
    file_path: "{{ dest }}"
