
# single line occurance
- name: Set a fact for the from xxx import xxx statement changes
  set_fact:
    current: "^from ansible.module_utils.network.{{ platform }}"
    new: "from ansible_collections.{{ collection_namespace }}.{{ collection_name }}.plugins.module_utils.network.{{ platform }}"

- name: "Update the import statements in {{ dest }}"
  replace:
    path: "{{ file_path }}"
    regexp: "{{ current }}"
    replace: "{{ new }}"

# multline split at network
- name: Set a fact for the from xxx import xxx statement changes
  set_fact:
    current: '^from ansible.module_utils.network.\s+\\\n\s+{{ platform }}(.*)'
    new: 'from ansible_collections.{{ collection_namespace }}.{{ collection_name }}.plugins.module_utils.network.{{ platform }}\1'

- name: "Update the import statements in {{ dest }}"
  replace:
    path: "{{ file_path }}"
    regexp: "{{ current }}"
    replace: "{{ new }}"

# split any long line we may have created
- name: Set a fact for the from xxx import xxx statement changes
  set_fact:
    current: 'from ansible_collections.{{ collection_namespace }}.{{ collection_name }}.plugins.module_utils.network.{{ platform }}(.*)'
    new: |
      from ansible_collections.{{ collection_namespace }}.{{ collection_name }}.plugins.module_utils.network. \
        {{ platform }}\1

- name: "Update the import statements in {{ dest }}"
  replace:
    path: "{{ file_path }}"
    regexp: "{{ current }}"
    replace: "{{ new }}"
