
- name: Start fresh every time
  file:
    state: absent
    path: "{{ collection_parent }}"

- name: Clone the repo
  git:
    repo: "git@github.com:ansible-network/ansible_collections.{{ collection_namespace }}.{{ platform }}.git"
    dest: "{{ destination_directory }}/{{ collection_namespace }}/{{ platform }}"

- name: Create a new branch
  shell: "cd {{ collection_parent }} && git checkout -t -b ansible_sha_{{ ansible_sha }}"
