
- name: Start fresh every time
  file:
    state: absent
    path: "{{ collection_parent }}"

- name: Clone the repo
  git:
    repo: "https://github.com/ansible-network/ansible_collections.{{ collection_namespace }}.{{ platform }}.git"
    dest: "{{ collection_parent }}"
